### ISSUE TITLE
Creation of segments out of different vessels systems

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#134]
Now, the centerline extraction for a given set of points works if all those points have been associated to the same model (e.g., 2 points assigned to portal). We would like to expand the use case to include the possibility to add points in different vessels systems.

 As an example, think about  the possibility to add 2 points in portal and 2 points in hepatic for the same point set. At this point, the algorithm for centerline extraction will look to connect the two systems (and will fail because the models should not have any connection).

Idea on how to implement this:
  - Instead of saving list of points, we could save list of tuples (model, point).
  - The algorithm that computes the centerlines will iterate over the number of models added in the list of tuples and will runt the centerline extraction as many times with the relevant points.
  - The id of the centerline (and color) should be the same

**Comment by olevs** [comment]
I've added the functionality for testing out this functionality in the #137 pull request. Now centerline segments are added to the same model instead of being replaced when pressing the "Add Vessel Centerline Segment" button. As long as you use the same markups point list you will be adding segments to the same model. For this first implementation you will need to use the other Slicer widgets to delete markup points or the combined centerline model.

**Comment by olevs** [comment]
Pull request #144 is adding segment id to all segment nodes. This can be used to give segments the same id. No GUI is created for this yet.
