### ISSUE TITLE
Some of the images for the slide-show in SlicerLiver are not present

### ISSUE THREAD

**Issue by RafaelPalomar** [ALive-research/Slicer-Liver#180]
When looking at the ExtensionManager, some of the images for SlicerLiver (slideshow) seem to be not present. Worth checking paths, image formats, etc.

**Comment by RafaelPalomar** [comment]
I have just checked the paths that we have set in the repository. We can
keep this open for some more testing, but the paths are pointing to
images delivered through GitHub (no errors)

**Comment by jamesobutler** [comment]
@RafaelPalomar Every other image is blank in the ExtensionManager SlicerLiver slideshow because it appears you have 2 spaces between the listed screenshot URLs rather than a single space. I would suspect this is why there are empty images in the slideshow. 

https://github.com/Slicer/ExtensionsIndex/blob/a71a9cd18ad99282d4f33a28cef04010818b682f/SlicerLiver.s4ext#L40-L41

**Comment by RafaelPalomar** [comment]
@jamesobutler, thanks a lot for the tip. Yes, it should be that.
